# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'CleverParents' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CleverParents
  platform :ios, "9.0"
  #网络请求
  pod 'AFNetworking'
#  pod 'GTSDK', '2.0.0.0-noidfa'
#
#
#  target 'NotificationService' do
#      platform :ios, "10.0"
#      pod 'GTExtensionSDK'
#  end

end
